### ISSUE TITLE
Problems while materializing InNBT card

### ISSUE THREAD

**Issue by Hiranus** [SCLeoX/IntegratedNBT#10] opened 2021-03-10 14:12 UTC
Please refer to [Bug in Integrated Dynamics](https://github.com/CyclopsMC/IntegratedDynamics/issues/1004) for details. Its 3rd issue in this bug report.
Basically I tried to use InNBT as a workaround for bug in InDy but result is the same - card is not materialized.

**Comment by SCLeoX** [comment] 2021-03-11 14:21
Thanks for reporting. Is the issue with materializing the NBT extraction cards or the pipe cards? If the issue is with pipe card, it *probably* has nothing to do with Integrated NBT. However, that said, I will watch the issue you linked. If it turns out that there are something need to be fixed in Integrated NBT, I will fix asap.

**Comment by SCLeoX** [comment] 2021-03-14 16:18
@Hiranus Is this fixed?

**Comment by SCLeoX** [comment] 2021-04-17 15:11
I assume it is fixed then.

**Closed by SCLeoX** 2021-04-17 15:11 UTC
Labels: Maybe bug idk
